export type Lang = "en" | "zh";

export const DEFAULT_LANG: Lang = "en";

export function parseLang(raw: string | undefined): Lang {
  return raw === "zh" ? "zh" : "en";
}

type Dict = Record<string, { en: string; zh: string }>;

const D: Dict = {
  siteName: { en: "Fintech Brief", zh: "金融科技早报" },
  navHome: { en: "Home", zh: "首页" },
  navBriefs: { en: "Briefs", zh: "早报归档" },
  navMarket: { en: "Market", zh: "行情" },
  navWatch: { en: "Watchlist", zh: "关注" },
  navAbout: { en: "About", zh: "关于" },
  heroKicker: { en: "Fintech · Daily Brief", zh: "Fintech · 每日早报" },
  heroTitle: { en: "Fintech Daily Brief", zh: "金融科技早报" },
  heroDesc: {
    en: "Daily fintech news summaries, original analysis, and US/ crypto market snapshots — auto-generated by Hermes Agent.",
    zh: "每日 fintech 新闻摘要、原创分析与美股 / 加密市场快照，由 Hermes Agent 自动生成。",
  },
  btnBriefs: { en: "Browse Briefs", zh: "浏览早报" },
  btnMarket: { en: "Live Market", zh: "实时行情" },
  langEn: { en: "EN", zh: "EN" },
  langZh: { en: "中", zh: "中" },
  latestBrief: { en: "Latest Brief", zh: "最新早报" },
  marketReview: { en: "Market Review", zh: "市场回顾" },
  news: { en: "News", zh: "新闻" },
  summary: { en: "Summary", zh: "总结" },
  colName: { en: "Name", zh: "标的" },
  colClose: { en: "Close", zh: "收盘" },
  colChg: { en: "Change", zh: "涨跌" },
  noBrief: { en: "No brief yet. Waiting for the next push…", zh: "暂无早报。等待下次推送…" },
  archives: { en: "Brief Archives", zh: "早报归档" },
  backToArchives: { en: "← Back to archives", zh: "← 返回归档" },
  notFound: { en: "Brief not found for", zh: "未找到以下日期的早报：" },
  marketBoard: { en: "Market Board", zh: "行情看板" },
  refresh5: { en: "Refreshes every 5 min", zh: "每 5 分钟刷新" },
  loading: { en: "Loading…", zh: "加载中…" },
  error: { en: "Error:", zh: "出错：" },
  secIndices: { en: "Indices", zh: "大盘指数" },
  secHoldings: { en: "Holdings", zh: "关注" },
  secCrypto: { en: "Crypto", zh: "加密货币" },
  asOf: { en: "Source: Yahoo Finance · as of", zh: "数据来源：Yahoo Finance · 更新于" },
  watchlist: { en: "Watchlist", zh: "关注" },
  wlNote: {
    en: "Add tickers in server config (data/watchlist.json).",
    zh: "关注列表可在服务器配置中添加（data/watchlist.json）。",
  },
  aboutTitle: { en: "About", zh: "关于" },
  aboutIntro: {
    en: "This site auto-generates a fintech daily brief via Hermes Agent, with news summaries, original analysis, and US/ crypto market data.",
    zh: "本网站由 Hermes Agent 自动生成金融科技早报，内容包含 fintech 新闻摘要、原创分析以及美股/加密市场数据。",
  },
  policyTitle: { en: "Content Policy", zh: "内容政策" },
  policy1: {
    en: "News is summarized (1–2 sentences) with source attribution and original analysis — no full-text reprints.",
    zh: "新闻仅作摘要（1-2 句）+ 来源标注 + 原创分析，不转载全文。",
  },
  policy2: {
    en: "Market data comes from the public Yahoo Finance API, for reference only.",
    zh: "行情数据来自 Yahoo Finance 公开接口，仅供信息参考。",
  },
  policy3: {
    en: "No personalized buy/sell advice, profit promises, or paid stock picks.",
    zh: "不提供个性化买卖建议、收益承诺或收费荐股。",
  },
  disclaimerTitle: { en: "Disclaimer", zh: "免责声明" },
  disclaimer: {
    en: "All content (briefs, analysis, market data) is for informational and educational purposes only, not investment advice. Investing carries risk; decisions are your own responsibility.",
    zh: "本网站所有内容（早报、分析、市场数据）仅供参考与教育用途，不构成任何投资建议。投资有风险，决策需谨慎。使用者应自行承担所有交易后果。",
  },
  techTitle: { en: "Tech Stack", zh: "技术栈" },
  tech: {
    en: "Next.js 16 · TypeScript · Tailwind CSS · deployed on Vercel (blog.yupion.com).",
    zh: "Next.js 16 · TypeScript · Tailwind CSS · 部署于 Vercel（blog.yupion.com）。",
  },
  footerNote: {
    en: "Source: Yahoo Finance. Site: blog.yupion.com. For reference only, not investment advice.",
    zh: "数据来源：Yahoo Finance。本站地址 blog.yupion.com，内容仅供参考，不构成任何投资建议。",
  },
  footerCopy: { en: "© {y} Kairos · Fintech Brief", zh: "© {y} Kairos · 金融科技早报" },
};

export function t(lang: Lang, key: keyof typeof D): string {
  return D[key][lang];
}

export function tpl(lang: Lang, key: keyof typeof D, vars: Record<string, string | number>): string {
  let s = D[key][lang];
  for (const [k, v] of Object.entries(vars)) s = s.replace(`{${k}}`, String(v));
  return s;
}
